### ISSUE TITLE
AttributeError: 'operator.attrgetter' object has no attribute '__qualname__'

### ISSUE THREAD

**Issue by antonagestam** [antonagestam/phantom-types#137]
```
>>> compose2(print, attrgetter("a.b"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/anton/.pyenv/versions/gina-api/lib/python3.9/site-packages/phantom/fn.py", line 26, in compose2
    b_name = _name(b)
  File "/Users/anton/.pyenv/versions/gina-api/lib/python3.9/site-packages/phantom/fn.py", line 9, in _name
    return fn.__qualname__
AttributeError: 'operator.attrgetter' object has no attribute '__qualname__'
```

This should fall back to `__name__` and when that doesn't exist either, should fall back to `__str__()`.

**Comment by muhdhisham** [comment]
I'm new to open source, can you please tell how to get started to resolve this issue.

**Comment by muhdhisham** [comment]
Sorry did not understand it completely. Is this what is to be done?
```
def _name(fn: Callable) -> str:
    if isinstance(fn, partial):
        fn = fn.func
        return fn.__qualname__
    return str(fn)

```

**Comment by antonagestam** [comment]
@muhdhisham No, that's not quite it. To explain in a doctest style, the `_name` function should behave like this:

```python
>>> from functools import partial
>>> _name(partial(int))
"int"
>>> class A:
...   class B:
...     ...
>>> _name(A.B)
"A.B"
>>> from operator import attrgetter, itemgetter
>>> _name(attrgetter("attrib"))
"operator.attrgetter('attrib')"
>>> _name(itemgetter("key"))
"operator.itemgetter('key')"
```

So, when trying to access `fn.__qualname__` fails with an `AttributeError`, the function should instead return `str(fn)`.
